force-app/main/default/objects/UserToDoVideos__c/UserToDoVideos__c.object-meta.xml
<CustomObject>
    <description>Stores the link to to do videos and there subtitles for a user.</description>
    <label>UserToDoVideo</label>
    <nameField>
        <label>UserToDoVideos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserToDoVideos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserToDoVideos__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserToDoVideos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserToDoVideos__c/fields/VideoExternalId__c.field-meta.xml
<CustomField>
    <fullName>VideoExternalId__c</fullName>
    <description>External id of video on Synthesia platform</description>
    <label>VideoExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserToDoVideos__c/fields/VideoSubtitleLink__c.field-meta.xml
<CustomField>
    <fullName>VideoSubtitleLink__c</fullName>
    <description>Link to subtitles of video which are stored in Salesforce</description>
    <label>VideoSubtitleLink</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UserToDoVideos__c/fields/VideoURl__c.field-meta.xml
<CustomField>
    <fullName>VideoURl__c</fullName>
    <description>Downloadable url of video</description>
    <label>VideoURl</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/DealDawgAIController.cls
/* Purpose - Class acts as controller for DealDawgAIVideoPlayer lwc component.
 *           handles database interactions for DealDawgAIVideoPlayer lwc component.
 * Author  - Amarjit Singh
 */
public with sharing class DealDawgAIController {  
    
    @AuraEnabled
    public static VideoDetailsResponse fetchTodaysToDoVideo() {     
        UserToDoVideos__c userVideo = [SELECT id,VideoExternalId__c,VideoSubtitleLink__c,VideoURl__c FROM UserToDoVideos__c WHERE User__c =: UserInfo.getUserId() order by createddate desc LIMIT 1];      
        VideoDetailsResponse response = new VideoDetailsResponse();
        response.videoUrl = userVideo.VideoURl__c;
        response.subtitleVtt = userVideo.VideoSubtitleLink__c;
        return response;
    }

    public class VideoDetailsResponse {
        @AuraEnabled public String videoUrl;
        @AuraEnabled public String subtitleVtt;
    }

    public class Captions {
        public String vtt;
        public String srt;
    }
}