force-app/main/default/objects/UserToDoVideos__c/UserToDoVideos__c.object-meta.xml
<CustomObject>
    <description>Stores the link to to do videos and there subtitles for a user.</description>
    <label>UserToDoVideo</label>
    <nameField>
        <label>UserToDoVideos Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserToDoVideos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/UserToDoVideos__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>UserToDoVideos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/UserToDoVideos__c/fields/VideoExternalId__c.field-meta.xml
<CustomField>
    <fullName>VideoExternalId__c</fullName>
    <description>External id of video on Synthesia platform</description>
    <label>VideoExternalId</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/UserToDoVideos__c/fields/VideoSubtitleLink__c.field-meta.xml
<CustomField>
    <fullName>VideoSubtitleLink__c</fullName>
    <description>Link to subtitles of video which are stored in Salesforce</description>
    <label>VideoSubtitleLink</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/UserToDoVideos__c/fields/VideoURl__c.field-meta.xml
<CustomField>
    <fullName>VideoURl__c</fullName>
    <description>Downloadable url of video</description>
    <label>VideoURl</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/AIVideoFetchService.cls
public with sharing class AIVideoFetchService {
    public static void retrieveGeneratedVideo(){
        UserToDoVideos__c userVideo = [SELECT id,VideoExternalId__c,VideoSubtitleLink__c,VideoURl__c FROM UserToDoVideos__c WHERE User__c =: UserInfo.getUserId() order by createddate desc LIMIT 1];
         makeGetCallout(userVideo);
    }

    public static void makeGetCallout(UserToDoVideos__c userVideo){
        String relativePath = '/videos/'+userVideo.VideoExternalId__c;
        String NAMED_CREDENTIAL = 'callout:synthesia';
        HttpRequest req = new HttpRequest();
        req.setEndpoint(NAMED_CREDENTIAL + relativePath); // Appends to the base URL
        req.setMethod('GET');
        req.setHeader('accept', 'application/json'); 

        Http http = new Http();
        HttpResponse res = http.send(req);
        System.debug('res '+res.getBody());
        System.debug('res '+res.getStatusCode());
        if (res.getStatusCode() == 200) {
            Map<String, Object> result = (Map<String, Object>) JSON.deserializeUntyped(res.getBody());
            Map<String, Object> captions = (Map<String, Object>) result.get('captions');
            String tempSubtitleName = 'Subtitle '+System.today();
            VttFileService.UploadResult upResult = VttFileService.downloadAndStoreVttFile((String) captions.get('vtt'),tempSubtitleName);
            userVideo.VideoURl__c = (String) result.get('download');
            userVideo.VideoSubtitleLink__c = upResult.fileUrl;
            update userVideo;
        } else {
            throw new AuraHandledException('Failed to get video URL. Status: ' + res.getStatus());
        }
    }
}